### ISSUE TITLE
Regarding resources it would be nice if you parsed /mappings from actuator

### ISSUE THREAD

**Issue by ssouris** [ordina-jworks/microservices-dashboard-server#29]
Hi,

I love your work, it's a great project and I totally want to use it in my day job.

Searching through the code I found out that you are trying to parse the microservice rest api home url, but what if an api does not expose link structure there.

Spring boot actuator exposes "/mappings" endpoint where you can parse the endpoints as an alternative. 
Do you have any plans for doing that?

Thanks for your time.

**Comment by andreasevers** [comment]
Hey @ssouris, it's a feature we planned for quite some time.
There is a ticket open for this already here: #4 

It normally isn't included in our first release but perhaps we should squeeze it in.
Normally people don't use indexes with hypermedia so using the `/mappings` endpoint is quite obvious.

I'll put a priority on it and you can expect it within the next couple of days. If you can't wait that long, feel free to submit a pull request for it :)

Oh and thanks for using our dashboard. We'll make sure we will do all we can to support you!

**Comment by andreasevers** [comment]
This kind of relates to documentation as well as you had to sift through the code to find out how the index aggregator works. Created an issue to track the documentation work: #30

**Comment by andreasevers** [comment]
Please try out the solution @ssouris available in the latest `SNAPSHOT`, any feedback is welcome.
Documentation is yet to be written (tracked in #30).
