### ISSUE TITLE
In the demo, group is selectable ..

### ISSUE THREAD

**Issue by bart-blommaerts** [ordina-jworks/microservices-dashboard-server#36]
![image](https://cloud.githubusercontent.com/assets/3988458/17347672/3cd29ab8-58c6-11e6-9dad-a15ded6bbe97.png)

When adding a node when no groups are existing yet, the group dropdown box is selectable, but it doesn't contain any content.

**Comment by andreasevers** [comment]
This belongs in the main UI repository: https://github.com/ordina-jworks/microservices-dashboard
Could you please create an issue there?
