### ISSUE TITLE
Custom Health Check endpoints -Consul discovery

### ISSUE THREAD

**Issue by rbkumar88** [ordina-jworks/microservices-dashboard-server#46]
Hi,

I am running microservices-dashboard server and UI separately and I could see the service is registered in Consul (using custom health check endpoint instead of the one provided by actuator). But I couldnt see any of my services in the ms-dashboard UI.

Is there any property I need to set inside server?

Thanks

**Comment by andreasevers** [comment]
Hey @rbkumar88,

It seems that our autoconfiguration condition is focused on eureka.
We're planning to release an initial 1.0.1 bugfix release today or tomorrow, and we'll fix this issue there as well.

Stay tuned!

**Comment by andreasevers** [comment]
For now you can add a bean implementing the `UriResolver` interface for your custom health check endpoints.
Just to be sure, is your UI calling the `/graph` endpoint of the server? (check the network tab of the developer tools in Chrome)

I'm working on better integration with Consul, as the autoconfiguration is Eureka-oriented now. Will post updates tomorrow during the day.
