### ISSUE TITLE
Use information given by spring-boot-maven-plugin

### ISSUE THREAD

**Issue by bokc** [ordina-jworks/microservices-dashboard-server#53]
When you use the plugin spring-boot-maven-plugin on build-info goal you get properties like name, version,... you can acces this data via the info  management endpoint. The look like this :
```
{
  "component": "MS Dashboard",
  "build": {
    "version": "0.0.1-SNAPSHOT",
    "artifact": "dashboard",
    "name": "MicroService Dashboard",
    "group": "com.wps.ms",
    "time": 1490110229000
  }
}
```

It cool be helpfull to use it.

**Comment by andreasevers** [comment]
Good idea. We'd need to apply very similar logic for this as we do for the health endpoint.
If you need this fast, you could consider filing a pull requests, and we'd be very happy to include this in the upcoming release!

**Comment by TYsewyn** [comment]
Closing this issue in favor #65 .
If you still have any questions, don't hesitate to reach out on Gitter or open a new issue.
