### ISSUE TITLE
RxNetty version update

### ISSUE THREAD

**Issue by jonatan-ivanov** [ordina-jworks/microservices-dashboard-server#60]
microservices-dashboard-server 1.0.x [uses](https://github.com/ordina-jworks/microservices-dashboard-server/blob/1.0.x/microservices-dashboard-server/pom.xml#L236) `io.reactivex:rxnetty:0.5.1`.

This is an unintentional release (from 0.4.x) which should not be used.
See [readme](https://github.com/ReactiveX/RxNetty#unintentional-release-artifacts) and issue [#439](https://github.com/ReactiveX/RxNetty/issues/439).

**Comment by andreasevers** [comment]
Well spotted!

I'll try to get it resolved ASAP.

**Comment by TYsewyn** [comment]
Thanks for letting us know!
We are aware of the issue and are currently checking multiple solutions while keeping future development in mind.

**Comment by TYsewyn** [comment]
Closing this issue in favor of version 2.x.
Version 1.x hasn't been maintained for over a year now and is now EOL.
