### ISSUE TITLE
Basic auth on sensitive actuator endpoint

### ISSUE THREAD

**Issue by silentFred** [ordina-jworks/microservices-dashboard-server#61]
Hi there, 

Thank you for your contribution! I'm very keen to start using the dashboard.
I see the mappings actuator endpoint is used to the resource column. I protect my sensitive endpoints with basic auth. Any way the dashboard can be configured to use that to fetch required data from mappings endpoint?

Kind regards,
Fred

**Comment by andreasevers** [comment]
Hey @silentFred, great question. It should be possible thanks to the security features added in the latest release. I suppose the docs aren't up to date. I'll have a look ASAP.

**Comment by andreasevers** [comment]
What we currently support, aside from OAuth2, is applying the inbound authorization header to the outgoing aggregator requests. To achieve this:
- Set property `msdashboard.security.strategies.forward-inbound-auth-header` to `mappings,index,health,pacts`.
- Add a basic Authentication header to the requests into the dashboard.

I'm checking if there's an easier way to do it. Shouldn't be hard. I'll get back to you.

**Comment by silentFred** [comment]
Thanks @andreasevers! Appreciate your help on this one! P.S has there ever been talk of merging this project with SBA? Feels like a good fit =)

**Comment by andreasevers** [comment]
If you don't wish to add a basic Authentication header to the requests into the dashboard (which is a bit tricky), you can try adding a Filter bean:
```java
@Component
public class BasicAuthFilter extends GenericFilterBean {

  @Override
  public void doFilter(final ServletRequest req,
             final ServletResponse res,
             final FilterChain chain) throws IOException, ServletException {
    AuthorizationHeaderHolder.set("Basic QWxhZGRpbjpPcGVuU2VzYW1l");
    chain.doFilter(req, res);
  }
}
```
Of course with `QWxhZGRpbjpPcGVuU2VzYW1l` being your own value (to construct check [here](https://en.wikipedia.org/wiki/Basic_access_authentication#Client_side)).

Integration with SBA can be tracked [here](https://github.com/ordina-jworks/microservices-dashboard-server/issues/41).

**Comment by TYsewyn** [comment]
Closing this because the question looks to be answered
