### ISSUE TITLE
Simple regex based service filtering

### ISSUE THREAD

**Issue by Guchman** [ordina-jworks/microservices-dashboard-server#63]
The only available mechanics to filter unwanted services is to exclude full names in filteredServices.
It's not very flexible. 
For example. We're using consul + registrator. So there is a bunch of services that didn't expose actuator endpoints registered in consul.
Maybe it's will be better to have "includeFilters" and "excludeFilters" that allows some simple regexp.
Like
```yaml
includeFilters:
   - "*-api"
   - "*-service-*"
```
I could do that if authors accept that feature.

**Comment by TYsewyn** [comment]
This will be possible in 2.0 by creating an instance of `ApplicationFilter` or `ApplicationInstanceFilter`.
Unfortunately the 1.x release had a lot of flaws and wasn't maintained.
Therefor I'm going to close this issue.

If you still have any questions, don't hesitate to reach out on Gitter or reopen this issue.
